settings:
  title: '悟元网站状态'
  url: 'https://status.wuyuan.dev/' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统均可运行'
  notAllmonitorsOperational: '并非所有系统都可运行'
  monitorLabelOperational: '可操作'
  monitorLabelNotOperational: '不可操作'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: wuyuan.dev
    name: 博客主站
    description: '孙悟元的博客主站'
    url: 'https://wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: cdm.wuyuan.dev
    name: CDM-网易云音乐在线下载
    description: '在线下载网易云音乐'
    url: 'https://cdm.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 

