settings:
  title: '悟元网站状态'
  url: 'https://status.wuyuan.dev/' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统均可运行'
  notAllmonitorsOperational: '并非所有系统都可运行'
  monitorLabelOperational: '可操作'
  monitorLabelNotOperational: '不可操作'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: wuyuan.dev
    name: 博客主站
    description: '孙悟元的博客主站'
    url: 'https://wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: cdm.wuyuan.dev
    name: CDM-网易云音乐在线下载
    description: '在线下载网易云音乐'
    url: 'https://cdm.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 


  - id: ourwlord.wuyuan.dev
    name: OurWlord社区
    description: 'OurWlord社区'
    url: 'https://ourwlord.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: url.wuyuan.dev
    name: 短连接
    description: '短连接'
    url: 'https://goweb.tk'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: 2103.wuyuan.dev
    name: 班级官网
    description: '志同心齐，同天共创'
    url: 'https://2103.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: cdn.wuyuan.dev
    name: CDN
    description: '其实就是图床...'
    url: 'https://cdn.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 


  - id: img.wuyuan.dev
    name: 图床
    description: '其实就是另一个图床...'
    url: 'https://img.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
  
  - id: longlink.wuyuan.dev
    name: 长链接
    description: '怎么说捏...'
    url: 'https://longlink.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 

- id: opentuling.wuyuan.dev
    name: OpenTuling
    description: '开放图灵？？？'
    url: 'https://opentuling.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
 
  - id: scratchgui.wuyuan.dev
    name: ScratchGui
    description: 'emmm'
    url: 'https://img.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
 
 - id: ydj.wuyuan.dev
    name: 秦氏工作室
    description: '其实就是个摆设...'
    url: 'https://ydj.wuyuan.dev'
    method: GET
    expectStatus: 200
    linkable: true 
    
